### ISSUE TITLE
Breakout base.py into functional classes, and move utils functions to a utils.py class. 

### ISSUE THREAD

**Issue by punkrokk** [Syncurity/msg-extractor#1]
We should break out base.py to be easier to understood by a new user. 

**Documentation:**  
Link to, or put here - documentation about what each class does (e.g. the "class" docstrings)

**Checklist**:  

- [x] Break out work here
- [x] solve for global debug
- [x] Testing
- [ ] Docs and readme update
- [ ] Pass codacy
- [x] CHANGELOG update

**Comment by TheElementalOfDestruction** [comment]
Pass Codacy is not going to happen due to the way some things are currently handled. We have two options when it comes to all the properties like header, body, htmlbody, etc.: Either we load them all into memory when the class is initialized or we  load them in when they are accessed. Right now the program currently does the latter.

**Comment by TheElementalOfDestruction** [comment]
By the way, I'll add some docstrings of my own to each of the things, but please feel free to go and modify the format of them however you like.

**Comment by punkrokk** [comment]
I’m a fan of: https://sphinxcontrib-napoleon.readthedocs.io/en/latest/example_google.html



Cheers,

JP

**Comment by TheElementalOfDestruction** [comment]
I don't like touching docstrings personally. Its just a lot of work. I'm going to separate that into a separate issue.
